version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      DB_HOST: dpg-ct1kpl2ng1s73e7cvqg-a
      DB_USER: intercityexpress_user
      DB_PASS: BfzQgG46egXkd5ubkJa2CITGUI8AGLWg
      DB_NAME: intercityexpress
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      DB_USER: intercityexpress_user
      DB_PASS: BfzQgG46egXkd5ubkJa2CITGUI8AGLWg
      DB_NAME: intercityexpress
    volumes:
      - db_data:/var/lib/postgresql/data

  pdf:
    build:
      context: .
      dockerfile: Dockerfile.pdf
    ports:
      - "5000:5000"

volumes:
  db_data:
