version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: yourpassword
      DB_NAME: intercityexpress
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: intercityexpress
    volumes:
      - db_data:/var/lib/postgresql/data

  pdf:
    build:
      context: .
      dockerfile: Dockerfile.pdf
    ports:
      - "5000:5000"

volumes:
  db_data:
