version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      DB_HOST: db
      DB_USER: vickspanda_user
      DB_PASS: f9bkm3PUogNzIS2MSQi5qW35j093X9IW
      DB_NAME: vickspanda
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: vickspanda_user
      POSTGRES_PASSWORD: f9bkm3PUogNzIS2MSQi5qW35j093X9IW
      POSTGRES_DB: vickspanda
    volumes:
      - db_data:/var/lib/postgresql/data

  pdf:
    build:
      context: .
      dockerfile: Dockerfile.pdf
    ports:
      - "5000:5000"

volumes:
  db_data:
